### ISSUE TITLE
[REWRITE] Full bot rewrite

### ISSUE THREAD

**Issue by TheChilliPL** [TheChilliPL/busker#14]
The whole bot is going to be rewritten with the following goals in mind:
- [ ] Not using discord-player as its backend (previously tracked using #3), using a custom backend and DI (dependency injection) instead
- [ ] Errors should be handled properly (previously tracked using #4)
- [ ] Highly configurable, with a huge amount of options (see also #2, #5, #7)
- [ ] With a clear Discord-based UI (see also #8)

(The issues above have been closed due to the rewrite)
